services:
  db_postgres_students:
    image: postgres
    container_name: db_postgres_students
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg_pratica_docker:/var/lib/postgresql/data

  node:
    container_name: node_students
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_students
    env_file:
      - .env
volumes:
  pg_pratica_docker: